INSERT INTO TeamMascot VALUES ("Lions", "Lion");
INSERT INTO TeamMascot VALUES ("Tigers", "Tiger");
INSERT INTO TeamMascot VALUES ("Bears", "Bear");
INSERT INTO TeamMascot VALUES ("Spartans", "Spartan");
INSERT INTO TeamMascot VALUES ("Warriors", "Warrior");
INSERT INTO TeamMascot VALUES ("Giants", "Giant");
INSERT INTO TeamMascot VALUES ("Cardinals", "Cardinal");
INSERT INTO TeamMascot VALUES ("Anteaters", "Anteater");
INSERT INTO TeamMascot VALUES ("Sagehens", "Sagehen");
INSERT INTO TeamMascot VALUES ("Willows", "Willow");
INSERT INTO TeamMascot VALUES ("Tridents", "Trident");
INSERT INTO TeamMascot VALUES ("Creatures", "Creature");
INSERT INTO TeamMascot VALUES ("Poets", "Poet");
INSERT INTO TeamMascot VALUES ("Aardvarks", "Aardvark");
INSERT INTO TeamMascot VALUES ("Mascots", "Mascot");
INSERT INTO TeamMascot VALUES ("Doors", "Door");
INSERT INTO TeamMascot VALUES ("Turnips", "Turnip");
INSERT INTO TeamMascot VALUES ("Trumpets", "Trumpet");
INSERT INTO TeamMascot VALUES ("Snakes", "Snake");
INSERT INTO TeamMascot VALUES ("Griffins", "Griffin");
INSERT INTO TeamMascot VALUES ("Hounds", "Hound");
INSERT INTO TeamMascot VALUES ("Dragons", "Dragon");
INSERT INTO Team VALUES (1, "Lions", "San Francisco");
INSERT INTO Team VALUES (2, "Tigers", "Claremont");
INSERT INTO Team VALUES (3, "Bears", "Chicago");
INSERT INTO Team VALUES (4, "Spartans", "New York");
INSERT INTO Team VALUES (5, "Warriors", "Tuscaloosa");
INSERT INTO Team VALUES (6, "Giants", "Milwaukee");
INSERT INTO Team VALUES (7, "Cardinals", "Oakland");
INSERT INTO Team VALUES (8, "Anteaters", "Los Angeles");
INSERT INTO Team VALUES (9, "Sagehens", "Boston");
INSERT INTO Team VALUES (10, "Willows", "Seattle");
INSERT INTO Team VALUES (11, "Tridents", "Portland");
INSERT INTO Team VALUES (12, "Creatures", "Richmond");
INSERT INTO Team VALUES (13, "Poets", "Dallas");
INSERT INTO Team VALUES (14, "Aardvarks", "Houston");
INSERT INTO Team VALUES (15, "Mascots", "Denver");
INSERT INTO Team VALUES (16, "Doors", "Compton");
INSERT INTO Team VALUES (17, "Turnips", "San Francisco");
INSERT INTO Team VALUES (18, "Trumpets", "Claremont");
INSERT INTO Team VALUES (19, "Snakes", "Chicago");
INSERT INTO Team VALUES (20, "Griffins", "New York");
INSERT INTO Team VALUES (21, "Hounds", "Tuscaloosa");
INSERT INTO Team VALUES (22, "Dragons", "Milwaukee");
INSERT INTO Team VALUES (23, "Lions", "Oakland");
INSERT INTO Team VALUES (24, "Tigers", "Los Angeles");
INSERT INTO Team VALUES (25, "Bears", "Boston");
INSERT INTO Team VALUES (26, "Spartans", "Seattle");
INSERT INTO Team VALUES (27, "Warriors", "Portland");
INSERT INTO Team VALUES (28, "Giants", "Richmond");
INSERT INTO Team VALUES (29, "Cardinals", "Dallas");
INSERT INTO Team VALUES (30, "Anteaters", "Houston");
INSERT INTO Team VALUES (31, "Sagehens", "Denver");
INSERT INTO Team VALUES (32, "Willows", "Compton");
INSERT INTO Team VALUES (33, "Tridents", "San Francisco");
INSERT INTO Team VALUES (34, "Creatures", "Claremont");
INSERT INTO Team VALUES (35, "Poets", "Chicago");
