INSERT INTO User VALUES ("James Smith", "james.smith@gmail.com", "test1234");
INSERT INTO Coach VALUES (1, 53071);
INSERT INTO User VALUES ("John Johnson", "john.johnson@gmail.com", "test1234");
INSERT INTO Coach VALUES (2, 55787);
INSERT INTO User VALUES ("Robert Williams", "robert.williams@gmail.com", "test1234");
INSERT INTO Coach VALUES (3, 64546);
INSERT INTO User VALUES ("Michael Jones", "michael.jones@gmail.com", "test1234");
INSERT INTO Coach VALUES (4, 80677);
INSERT INTO User VALUES ("William Brown", "william.brown@gmail.com", "test1234");
INSERT INTO Coach VALUES (5, 60238);
INSERT INTO User VALUES ("David Davis", "david.davis@gmail.com", "test1234");
INSERT INTO Coach VALUES (6, 66693);
INSERT INTO User VALUES ("Richard Miller", "richard.miller@gmail.com", "test1234");
INSERT INTO Coach VALUES (7, 68575);
INSERT INTO User VALUES ("Charles Wilson", "charles.wilson@gmail.com", "test1234");
INSERT INTO Coach VALUES (8, 81468);
INSERT INTO User VALUES ("Joseph Moore", "joseph.moore@gmail.com", "test1234");
INSERT INTO Coach VALUES (9, 89172);
INSERT INTO User VALUES ("Thomas Taylor", "thomas.taylor@gmail.com", "test1234");
INSERT INTO Coach VALUES (10, 76972);
INSERT INTO User VALUES ("Christopher Anderson", "christopher.anderson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (11, 76, 220);
INSERT INTO User VALUES ("Daniel Thomas", "daniel.thomas@gmail.com", "test1234");
INSERT INTO Athlete VALUES (12, 65, 218);
INSERT INTO User VALUES ("Paul Jackson", "paul.jackson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (13, 77, 248);
INSERT INTO User VALUES ("Mark White", "mark.white@gmail.com", "test1234");
INSERT INTO Athlete VALUES (14, 69, 175);
INSERT INTO User VALUES ("Donald Harris", "donald.harris@gmail.com", "test1234");
INSERT INTO Athlete VALUES (15, 65, 161);
INSERT INTO User VALUES ("George Martin", "george.martin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (16, 65, 238);
INSERT INTO User VALUES ("Kenneth Thompson", "kenneth.thompson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (17, 72, 168);
INSERT INTO User VALUES ("Steven Garcia", "steven.garcia@gmail.com", "test1234");
INSERT INTO Athlete VALUES (18, 79, 158);
INSERT INTO User VALUES ("Edward Martinez", "edward.martinez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (19, 77, 175);
INSERT INTO User VALUES ("Brian Robinson", "brian.robinson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (20, 74, 156);
INSERT INTO User VALUES ("Ronald Clark", "ronald.clark@gmail.com", "test1234");
INSERT INTO Athlete VALUES (21, 78, 177);
INSERT INTO User VALUES ("Anthony Rodriguez", "anthony.rodriguez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (22, 72, 160);
INSERT INTO User VALUES ("Kevin Lewis", "kevin.lewis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (23, 68, 207);
INSERT INTO User VALUES ("Jason Lee", "jason.lee@gmail.com", "test1234");
INSERT INTO Athlete VALUES (24, 74, 153);
INSERT INTO User VALUES ("Matthew Walker", "matthew.walker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (25, 76, 166);
INSERT INTO User VALUES ("Gary Hall", "gary.hall@gmail.com", "test1234");
INSERT INTO Athlete VALUES (26, 76, 193);
INSERT INTO User VALUES ("Timothy Allen", "timothy.allen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (27, 80, 160);
INSERT INTO User VALUES ("Jose Young", "jose.young@gmail.com", "test1234");
INSERT INTO Athlete VALUES (28, 66, 180);
INSERT INTO User VALUES ("Larry Hernandez", "larry.hernandez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (29, 68, 190);
INSERT INTO User VALUES ("Jeffrey King", "jeffrey.king@gmail.com", "test1234");
INSERT INTO Athlete VALUES (30, 67, 221);
INSERT INTO User VALUES ("Frank Wright", "frank.wright@gmail.com", "test1234");
INSERT INTO Athlete VALUES (31, 67, 200);
INSERT INTO User VALUES ("Scott Lopez", "scott.lopez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (32, 74, 194);
INSERT INTO User VALUES ("Eric Hill", "eric.hill@gmail.com", "test1234");
INSERT INTO Athlete VALUES (33, 66, 173);
INSERT INTO User VALUES ("Stephen Scott", "stephen.scott@gmail.com", "test1234");
INSERT INTO Athlete VALUES (34, 68, 183);
INSERT INTO User VALUES ("Andrew Green", "andrew.green@gmail.com", "test1234");
INSERT INTO Athlete VALUES (35, 70, 166);
INSERT INTO User VALUES ("Raymond Adams", "raymond.adams@gmail.com", "test1234");
INSERT INTO Athlete VALUES (36, 66, 193);
INSERT INTO User VALUES ("Gregory Baker", "gregory.baker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (37, 66, 189);
INSERT INTO User VALUES ("Joshua Gonzalez", "joshua.gonzalez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (38, 72, 191);
INSERT INTO User VALUES ("Jerry Nelson", "jerry.nelson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (39, 75, 231);
INSERT INTO User VALUES ("Dennis Carter", "dennis.carter@gmail.com", "test1234");
INSERT INTO Athlete VALUES (40, 69, 249);
INSERT INTO User VALUES ("Walter Mitchell", "walter.mitchell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (41, 68, 244);
INSERT INTO User VALUES ("Patrick Perez", "patrick.perez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (42, 70, 168);
INSERT INTO User VALUES ("Peter Roberts", "peter.roberts@gmail.com", "test1234");
INSERT INTO Athlete VALUES (43, 75, 235);
INSERT INTO User VALUES ("Harold Turner", "harold.turner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (44, 70, 240);
INSERT INTO User VALUES ("Douglas Phillips", "douglas.phillips@gmail.com", "test1234");
INSERT INTO Athlete VALUES (45, 75, 233);
INSERT INTO User VALUES ("Henry Campbell", "henry.campbell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (46, 65, 190);
INSERT INTO User VALUES ("Carl Parker", "carl.parker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (47, 66, 245);
INSERT INTO User VALUES ("Arthur Evans", "arthur.evans@gmail.com", "test1234");
INSERT INTO Athlete VALUES (48, 73, 162);
INSERT INTO User VALUES ("Ryan Edwards", "ryan.edwards@gmail.com", "test1234");
INSERT INTO Athlete VALUES (49, 78, 248);
INSERT INTO User VALUES ("Roger Collins", "roger.collins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (50, 68, 157);
INSERT INTO User VALUES ("Joe Stewart", "joe.stewart@gmail.com", "test1234");
INSERT INTO Athlete VALUES (51, 79, 219);
INSERT INTO User VALUES ("Juan Sanchez", "juan.sanchez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (52, 71, 157);
INSERT INTO User VALUES ("Jack Morris", "jack.morris@gmail.com", "test1234");
INSERT INTO Athlete VALUES (53, 65, 178);
INSERT INTO User VALUES ("Albert Rogers", "albert.rogers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (54, 65, 248);
INSERT INTO User VALUES ("Jonathan Reed", "jonathan.reed@gmail.com", "test1234");
INSERT INTO Athlete VALUES (55, 68, 218);
INSERT INTO User VALUES ("Justin Cook", "justin.cook@gmail.com", "test1234");
INSERT INTO Athlete VALUES (56, 80, 174);
INSERT INTO User VALUES ("Terry Morgan", "terry.morgan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (57, 73, 200);
INSERT INTO User VALUES ("Gerald Bell", "gerald.bell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (58, 78, 242);
INSERT INTO User VALUES ("Keith Murphy", "keith.murphy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (59, 74, 151);
INSERT INTO User VALUES ("Samuel Bailey", "samuel.bailey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (60, 80, 166);
INSERT INTO User VALUES ("Willie Rivera", "willie.rivera@gmail.com", "test1234");
INSERT INTO Athlete VALUES (61, 77, 203);
INSERT INTO User VALUES ("Ralph Cooper", "ralph.cooper@gmail.com", "test1234");
INSERT INTO Athlete VALUES (62, 70, 230);
INSERT INTO User VALUES ("Lawrence Richardson", "lawrence.richardson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (63, 67, 236);
INSERT INTO User VALUES ("Nicholas Cox", "nicholas.cox@gmail.com", "test1234");
INSERT INTO Athlete VALUES (64, 80, 243);
INSERT INTO User VALUES ("Roy Howard", "roy.howard@gmail.com", "test1234");
INSERT INTO Athlete VALUES (65, 78, 214);
INSERT INTO User VALUES ("Benjamin Ward", "benjamin.ward@gmail.com", "test1234");
INSERT INTO Athlete VALUES (66, 67, 220);
INSERT INTO User VALUES ("Bruce Torres", "bruce.torres@gmail.com", "test1234");
INSERT INTO Athlete VALUES (67, 77, 186);
INSERT INTO User VALUES ("Brandon Peterson", "brandon.peterson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (68, 70, 195);
INSERT INTO User VALUES ("Adam Gray", "adam.gray@gmail.com", "test1234");
INSERT INTO Athlete VALUES (69, 69, 219);
INSERT INTO User VALUES ("Harry Ramirez", "harry.ramirez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (70, 77, 213);
INSERT INTO User VALUES ("Fred James", "fred.james@gmail.com", "test1234");
INSERT INTO Athlete VALUES (71, 75, 211);
INSERT INTO User VALUES ("Wayne Watson", "wayne.watson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (72, 65, 203);
INSERT INTO User VALUES ("Billy Brooks", "billy.brooks@gmail.com", "test1234");
INSERT INTO Athlete VALUES (73, 77, 185);
INSERT INTO User VALUES ("Steve Kelly", "steve.kelly@gmail.com", "test1234");
INSERT INTO Athlete VALUES (74, 66, 155);
INSERT INTO User VALUES ("Louis Sanders", "louis.sanders@gmail.com", "test1234");
INSERT INTO Athlete VALUES (75, 71, 207);
INSERT INTO User VALUES ("Jeremy Price", "jeremy.price@gmail.com", "test1234");
INSERT INTO Athlete VALUES (76, 79, 202);
INSERT INTO User VALUES ("Aaron Bennett", "aaron.bennett@gmail.com", "test1234");
INSERT INTO Athlete VALUES (77, 80, 240);
INSERT INTO User VALUES ("Randy Wood", "randy.wood@gmail.com", "test1234");
INSERT INTO Athlete VALUES (78, 65, 202);
INSERT INTO User VALUES ("Howard Barnes", "howard.barnes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (79, 65, 214);
INSERT INTO User VALUES ("Eugene Ross", "eugene.ross@gmail.com", "test1234");
INSERT INTO Athlete VALUES (80, 76, 183);
INSERT INTO User VALUES ("Carlos Henderson", "carlos.henderson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (81, 70, 154);
INSERT INTO User VALUES ("Russell Coleman", "russell.coleman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (82, 76, 244);
INSERT INTO User VALUES ("Bobby Jenkins", "bobby.jenkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (83, 75, 152);
INSERT INTO User VALUES ("Victor Perry", "victor.perry@gmail.com", "test1234");
INSERT INTO Athlete VALUES (84, 76, 245);
INSERT INTO User VALUES ("Martin Powell", "martin.powell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (85, 72, 175);
INSERT INTO User VALUES ("Ernest Long", "ernest.long@gmail.com", "test1234");
INSERT INTO Athlete VALUES (86, 76, 164);
INSERT INTO User VALUES ("Phillip Patterson", "phillip.patterson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (87, 70, 164);
INSERT INTO User VALUES ("Todd Hughes", "todd.hughes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (88, 65, 250);
INSERT INTO User VALUES ("Jesse Flores", "jesse.flores@gmail.com", "test1234");
INSERT INTO Athlete VALUES (89, 70, 234);
INSERT INTO User VALUES ("Craig Washington", "craig.washington@gmail.com", "test1234");
INSERT INTO Athlete VALUES (90, 71, 248);
INSERT INTO User VALUES ("Alan Butler", "alan.butler@gmail.com", "test1234");
INSERT INTO Athlete VALUES (91, 79, 234);
INSERT INTO User VALUES ("Shawn Simmons", "shawn.simmons@gmail.com", "test1234");
INSERT INTO Athlete VALUES (92, 66, 192);
INSERT INTO User VALUES ("Clarence Foster", "clarence.foster@gmail.com", "test1234");
INSERT INTO Athlete VALUES (93, 74, 225);
INSERT INTO User VALUES ("Sean Gonzales", "sean.gonzales@gmail.com", "test1234");
INSERT INTO Athlete VALUES (94, 65, 206);
INSERT INTO User VALUES ("Philip Bryant", "philip.bryant@gmail.com", "test1234");
INSERT INTO Athlete VALUES (95, 68, 221);
INSERT INTO User VALUES ("Chris Alexander", "chris.alexander@gmail.com", "test1234");
INSERT INTO Athlete VALUES (96, 76, 226);
INSERT INTO User VALUES ("Johnny Russell", "johnny.russell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (97, 69, 243);
INSERT INTO User VALUES ("Earl Griffin", "earl.griffin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (98, 80, 233);
INSERT INTO User VALUES ("Jimmy Diaz", "jimmy.diaz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (99, 74, 150);
INSERT INTO User VALUES ("Antonio Hayes", "antonio.hayes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (100, 73, 229);
INSERT INTO User VALUES ("Danny Myers", "danny.myers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (101, 68, 183);
INSERT INTO User VALUES ("Bryan Ford", "bryan.ford@gmail.com", "test1234");
INSERT INTO Athlete VALUES (102, 72, 150);
INSERT INTO User VALUES ("Tony Hamilton", "tony.hamilton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (103, 78, 197);
INSERT INTO User VALUES ("Luis Graham", "luis.graham@gmail.com", "test1234");
INSERT INTO Athlete VALUES (104, 69, 197);
INSERT INTO User VALUES ("Mike Sullivan", "mike.sullivan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (105, 76, 192);
INSERT INTO User VALUES ("Stanley Wallace", "stanley.wallace@gmail.com", "test1234");
INSERT INTO Athlete VALUES (106, 71, 230);
INSERT INTO User VALUES ("Leonard Woods", "leonard.woods@gmail.com", "test1234");
INSERT INTO Athlete VALUES (107, 80, 231);
INSERT INTO User VALUES ("Nathan Cole", "nathan.cole@gmail.com", "test1234");
INSERT INTO Athlete VALUES (108, 72, 219);
INSERT INTO User VALUES ("Dale West", "dale.west@gmail.com", "test1234");
INSERT INTO Athlete VALUES (109, 69, 204);
INSERT INTO User VALUES ("Manuel Jordan", "manuel.jordan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (110, 77, 167);
INSERT INTO User VALUES ("Rodney Owens", "rodney.owens@gmail.com", "test1234");
INSERT INTO Athlete VALUES (111, 65, 197);
INSERT INTO User VALUES ("Curtis Reynolds", "curtis.reynolds@gmail.com", "test1234");
INSERT INTO Athlete VALUES (112, 69, 217);
INSERT INTO User VALUES ("Norman Fisher", "norman.fisher@gmail.com", "test1234");
INSERT INTO Athlete VALUES (113, 72, 187);
INSERT INTO User VALUES ("Allen Ellis", "allen.ellis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (114, 72, 243);
INSERT INTO User VALUES ("Marvin Harrison", "marvin.harrison@gmail.com", "test1234");
INSERT INTO Athlete VALUES (115, 69, 172);
INSERT INTO User VALUES ("Vincent Gibson", "vincent.gibson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (116, 75, 190);
INSERT INTO User VALUES ("Glenn Mcdonald", "glenn.mcdonald@gmail.com", "test1234");
INSERT INTO Athlete VALUES (117, 73, 243);
INSERT INTO User VALUES ("Jeffery Cruz", "jeffery.cruz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (118, 69, 188);
INSERT INTO User VALUES ("Travis Marshall", "travis.marshall@gmail.com", "test1234");
INSERT INTO Athlete VALUES (119, 78, 214);
INSERT INTO User VALUES ("Jeff Ortiz", "jeff.ortiz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (120, 65, 191);
INSERT INTO User VALUES ("Chad Gomez", "chad.gomez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (121, 79, 166);
INSERT INTO User VALUES ("Jacob Murray", "jacob.murray@gmail.com", "test1234");
INSERT INTO Athlete VALUES (122, 72, 206);
INSERT INTO User VALUES ("Lee Freeman", "lee.freeman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (123, 67, 202);
INSERT INTO User VALUES ("Melvin Wells", "melvin.wells@gmail.com", "test1234");
INSERT INTO Athlete VALUES (124, 74, 228);
INSERT INTO User VALUES ("Alfred Webb", "alfred.webb@gmail.com", "test1234");
INSERT INTO Athlete VALUES (125, 72, 167);
INSERT INTO User VALUES ("Kyle Simpson", "kyle.simpson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (126, 77, 170);
INSERT INTO User VALUES ("Francis Stevens", "francis.stevens@gmail.com", "test1234");
INSERT INTO Athlete VALUES (127, 78, 173);
INSERT INTO User VALUES ("Bradley Tucker", "bradley.tucker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (128, 76, 151);
INSERT INTO User VALUES ("Jesus Porter", "jesus.porter@gmail.com", "test1234");
INSERT INTO Athlete VALUES (129, 78, 230);
INSERT INTO User VALUES ("Herbert Hunter", "herbert.hunter@gmail.com", "test1234");
INSERT INTO Athlete VALUES (130, 80, 183);
INSERT INTO User VALUES ("Frederick Hicks", "frederick.hicks@gmail.com", "test1234");
INSERT INTO Athlete VALUES (131, 69, 169);
INSERT INTO User VALUES ("Ray Crawford", "ray.crawford@gmail.com", "test1234");
INSERT INTO Athlete VALUES (132, 72, 224);
INSERT INTO User VALUES ("Joel Henry", "joel.henry@gmail.com", "test1234");
INSERT INTO Athlete VALUES (133, 70, 166);
INSERT INTO User VALUES ("Edwin Boyd", "edwin.boyd@gmail.com", "test1234");
INSERT INTO Athlete VALUES (134, 74, 168);
INSERT INTO User VALUES ("Don Mason", "don.mason@gmail.com", "test1234");
INSERT INTO Athlete VALUES (135, 65, 192);
INSERT INTO User VALUES ("Eddie Morales", "eddie.morales@gmail.com", "test1234");
INSERT INTO Athlete VALUES (136, 71, 169);
INSERT INTO User VALUES ("Ricky Kennedy", "ricky.kennedy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (137, 79, 250);
INSERT INTO User VALUES ("Troy Warren", "troy.warren@gmail.com", "test1234");
INSERT INTO Athlete VALUES (138, 71, 232);
INSERT INTO User VALUES ("Randall Dixon", "randall.dixon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (139, 69, 184);
INSERT INTO User VALUES ("Barry Ramos", "barry.ramos@gmail.com", "test1234");
INSERT INTO Athlete VALUES (140, 67, 202);
INSERT INTO User VALUES ("Alexander Reyes", "alexander.reyes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (141, 78, 201);
INSERT INTO User VALUES ("Bernard Burns", "bernard.burns@gmail.com", "test1234");
INSERT INTO Athlete VALUES (142, 71, 170);
INSERT INTO User VALUES ("Mario Gordon", "mario.gordon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (143, 68, 185);
INSERT INTO User VALUES ("Leroy Shaw", "leroy.shaw@gmail.com", "test1234");
INSERT INTO Athlete VALUES (144, 78, 157);
INSERT INTO User VALUES ("Francisco Holmes", "francisco.holmes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (145, 74, 186);
INSERT INTO User VALUES ("Marcus Rice", "marcus.rice@gmail.com", "test1234");
INSERT INTO Athlete VALUES (146, 79, 229);
INSERT INTO User VALUES ("Micheal Robertson", "micheal.robertson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (147, 67, 241);
INSERT INTO User VALUES ("Theodore Hunt", "theodore.hunt@gmail.com", "test1234");
INSERT INTO Athlete VALUES (148, 80, 165);
INSERT INTO User VALUES ("Clifford Black", "clifford.black@gmail.com", "test1234");
INSERT INTO Athlete VALUES (149, 65, 216);
INSERT INTO User VALUES ("Miguel Daniels", "miguel.daniels@gmail.com", "test1234");
INSERT INTO Athlete VALUES (150, 73, 215);
INSERT INTO User VALUES ("Oscar Palmer", "oscar.palmer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (151, 78, 192);
INSERT INTO User VALUES ("Jay Mills", "jay.mills@gmail.com", "test1234");
INSERT INTO Athlete VALUES (152, 70, 216);
INSERT INTO User VALUES ("Jim Nichols", "jim.nichols@gmail.com", "test1234");
INSERT INTO Athlete VALUES (153, 68, 233);
INSERT INTO User VALUES ("Tom Grant", "tom.grant@gmail.com", "test1234");
INSERT INTO Athlete VALUES (154, 67, 176);
INSERT INTO User VALUES ("Calvin Knight", "calvin.knight@gmail.com", "test1234");
INSERT INTO Athlete VALUES (155, 76, 192);
INSERT INTO User VALUES ("Alex Ferguson", "alex.ferguson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (156, 74, 201);
INSERT INTO User VALUES ("Jon Rose", "jon.rose@gmail.com", "test1234");
INSERT INTO Athlete VALUES (157, 67, 247);
INSERT INTO User VALUES ("Ronnie Stone", "ronnie.stone@gmail.com", "test1234");
INSERT INTO Athlete VALUES (158, 77, 166);
INSERT INTO User VALUES ("Bill Hawkins", "bill.hawkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (159, 66, 170);
INSERT INTO User VALUES ("Lloyd Dunn", "lloyd.dunn@gmail.com", "test1234");
INSERT INTO Athlete VALUES (160, 71, 159);
INSERT INTO User VALUES ("Tommy Perkins", "tommy.perkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (161, 72, 222);
INSERT INTO User VALUES ("Leon Hudson", "leon.hudson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (162, 66, 193);
INSERT INTO User VALUES ("Derek Spencer", "derek.spencer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (163, 77, 183);
INSERT INTO User VALUES ("Warren Gardner", "warren.gardner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (164, 66, 177);
INSERT INTO User VALUES ("Darrell Stephens", "darrell.stephens@gmail.com", "test1234");
INSERT INTO Athlete VALUES (165, 72, 210);
INSERT INTO User VALUES ("Jerome Payne", "jerome.payne@gmail.com", "test1234");
INSERT INTO Athlete VALUES (166, 77, 202);
INSERT INTO User VALUES ("Floyd Pierce", "floyd.pierce@gmail.com", "test1234");
INSERT INTO Athlete VALUES (167, 73, 234);
INSERT INTO User VALUES ("Leo Berry", "leo.berry@gmail.com", "test1234");
INSERT INTO Athlete VALUES (168, 78, 227);
INSERT INTO User VALUES ("Alvin Matthews", "alvin.matthews@gmail.com", "test1234");
INSERT INTO Athlete VALUES (169, 71, 208);
INSERT INTO User VALUES ("Tim Arnold", "tim.arnold@gmail.com", "test1234");
INSERT INTO Athlete VALUES (170, 78, 183);
INSERT INTO User VALUES ("Wesley Wagner", "wesley.wagner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (171, 67, 215);
INSERT INTO User VALUES ("Gordon Willis", "gordon.willis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (172, 78, 189);
INSERT INTO User VALUES ("Dean Ray", "dean.ray@gmail.com", "test1234");
INSERT INTO Athlete VALUES (173, 74, 213);
INSERT INTO User VALUES ("Greg Watkins", "greg.watkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (174, 74, 158);
INSERT INTO User VALUES ("Jorge Olson", "jorge.olson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (175, 68, 193);
INSERT INTO User VALUES ("Dustin Carroll", "dustin.carroll@gmail.com", "test1234");
INSERT INTO Athlete VALUES (176, 66, 213);
INSERT INTO User VALUES ("Pedro Duncan", "pedro.duncan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (177, 67, 153);
INSERT INTO User VALUES ("Derrick Snyder", "derrick.snyder@gmail.com", "test1234");
INSERT INTO Athlete VALUES (178, 69, 193);
INSERT INTO User VALUES ("Dan Hart", "dan.hart@gmail.com", "test1234");
INSERT INTO Athlete VALUES (179, 79, 157);
INSERT INTO User VALUES ("Lewis Cunningham", "lewis.cunningham@gmail.com", "test1234");
INSERT INTO Athlete VALUES (180, 77, 182);
INSERT INTO User VALUES ("Zachary Bradley", "zachary.bradley@gmail.com", "test1234");
INSERT INTO Athlete VALUES (181, 76, 246);
INSERT INTO User VALUES ("Corey Lane", "corey.lane@gmail.com", "test1234");
INSERT INTO Athlete VALUES (182, 69, 222);
INSERT INTO User VALUES ("Herman Andrews", "herman.andrews@gmail.com", "test1234");
INSERT INTO Athlete VALUES (183, 73, 218);
INSERT INTO User VALUES ("Maurice Ruiz", "maurice.ruiz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (184, 79, 216);
INSERT INTO User VALUES ("Vernon Harper", "vernon.harper@gmail.com", "test1234");
INSERT INTO Athlete VALUES (185, 68, 226);
INSERT INTO User VALUES ("Roberto Fox", "roberto.fox@gmail.com", "test1234");
INSERT INTO Athlete VALUES (186, 77, 154);
INSERT INTO User VALUES ("Clyde Riley", "clyde.riley@gmail.com", "test1234");
INSERT INTO Athlete VALUES (187, 67, 190);
INSERT INTO User VALUES ("Glen Armstrong", "glen.armstrong@gmail.com", "test1234");
INSERT INTO Athlete VALUES (188, 76, 171);
INSERT INTO User VALUES ("Hector Carpenter", "hector.carpenter@gmail.com", "test1234");
INSERT INTO Athlete VALUES (189, 79, 239);
INSERT INTO User VALUES ("Shane Weaver", "shane.weaver@gmail.com", "test1234");
INSERT INTO Athlete VALUES (190, 72, 214);
INSERT INTO User VALUES ("Ricardo Greene", "ricardo.greene@gmail.com", "test1234");
INSERT INTO Athlete VALUES (191, 67, 187);
INSERT INTO User VALUES ("Sam Lawrence", "sam.lawrence@gmail.com", "test1234");
INSERT INTO Athlete VALUES (192, 79, 187);
INSERT INTO User VALUES ("Rick Elliott", "rick.elliott@gmail.com", "test1234");
INSERT INTO Athlete VALUES (193, 65, 234);
INSERT INTO User VALUES ("Lester Chavez", "lester.chavez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (194, 65, 200);
INSERT INTO User VALUES ("Brent Sims", "brent.sims@gmail.com", "test1234");
INSERT INTO Athlete VALUES (195, 71, 174);
INSERT INTO User VALUES ("Ramon Austin", "ramon.austin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (196, 72, 162);
INSERT INTO User VALUES ("Charlie Peters", "charlie.peters@gmail.com", "test1234");
INSERT INTO Athlete VALUES (197, 65, 180);
INSERT INTO User VALUES ("Tyler Kelley", "tyler.kelley@gmail.com", "test1234");
INSERT INTO Athlete VALUES (198, 67, 170);
INSERT INTO User VALUES ("Gilbert Franklin", "gilbert.franklin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (199, 71, 186);
INSERT INTO User VALUES ("Gene Lawson", "gene.lawson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (200, 65, 181);
INSERT INTO User VALUES ("Marc Fields", "marc.fields@gmail.com", "test1234");
INSERT INTO Athlete VALUES (201, 76, 201);
INSERT INTO User VALUES ("Reginald Gutierrez", "reginald.gutierrez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (202, 74, 188);
INSERT INTO User VALUES ("Ruben Ryan", "ruben.ryan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (203, 65, 179);
INSERT INTO User VALUES ("Brett Schmidt", "brett.schmidt@gmail.com", "test1234");
INSERT INTO Athlete VALUES (204, 74, 184);
INSERT INTO User VALUES ("Angel Carr", "angel.carr@gmail.com", "test1234");
INSERT INTO Athlete VALUES (205, 74, 232);
INSERT INTO User VALUES ("Nathaniel Vasquez", "nathaniel.vasquez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (206, 72, 199);
INSERT INTO User VALUES ("Rafael Castillo", "rafael.castillo@gmail.com", "test1234");
INSERT INTO Athlete VALUES (207, 65, 150);
INSERT INTO User VALUES ("Leslie Wheeler", "leslie.wheeler@gmail.com", "test1234");
INSERT INTO Athlete VALUES (208, 69, 197);
INSERT INTO User VALUES ("Edgar Chapman", "edgar.chapman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (209, 68, 176);
INSERT INTO User VALUES ("Milton Oliver", "milton.oliver@gmail.com", "test1234");
INSERT INTO Athlete VALUES (210, 69, 217);
INSERT INTO User VALUES ("Raul Montgomery", "raul.montgomery@gmail.com", "test1234");
INSERT INTO Athlete VALUES (211, 72, 206);
INSERT INTO User VALUES ("Ben Richards", "ben.richards@gmail.com", "test1234");
INSERT INTO Athlete VALUES (212, 78, 190);
INSERT INTO User VALUES ("Chester Williamson", "chester.williamson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (213, 65, 237);
INSERT INTO User VALUES ("Cecil Johnston", "cecil.johnston@gmail.com", "test1234");
INSERT INTO Athlete VALUES (214, 73, 194);
INSERT INTO User VALUES ("Duane Banks", "duane.banks@gmail.com", "test1234");
INSERT INTO Athlete VALUES (215, 75, 169);
INSERT INTO User VALUES ("Franklin Meyer", "franklin.meyer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (216, 74, 191);
INSERT INTO User VALUES ("Andre Bishop", "andre.bishop@gmail.com", "test1234");
INSERT INTO Athlete VALUES (217, 69, 235);
INSERT INTO User VALUES ("Elmer Mccoy", "elmer.mccoy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (218, 67, 190);
INSERT INTO User VALUES ("Brad Howell", "brad.howell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (219, 69, 212);
INSERT INTO User VALUES ("Gabriel Alvarez", "gabriel.alvarez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (220, 70, 222);
INSERT INTO User VALUES ("Ron Morrison", "ron.morrison@gmail.com", "test1234");
INSERT INTO Athlete VALUES (221, 78, 236);
INSERT INTO User VALUES ("Mitchell Hansen", "mitchell.hansen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (222, 66, 184);
INSERT INTO User VALUES ("Roland Fernandez", "roland.fernandez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (223, 73, 174);
INSERT INTO User VALUES ("Arnold Garza", "arnold.garza@gmail.com", "test1234");
INSERT INTO Athlete VALUES (224, 71, 170);
INSERT INTO User VALUES ("Harvey Harvey", "harvey.harvey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (225, 80, 177);
INSERT INTO User VALUES ("Jared Little", "jared.little@gmail.com", "test1234");
INSERT INTO Athlete VALUES (226, 70, 156);
INSERT INTO User VALUES ("Adrian Burton", "adrian.burton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (227, 70, 239);
INSERT INTO User VALUES ("Karl Stanley", "karl.stanley@gmail.com", "test1234");
INSERT INTO Athlete VALUES (228, 76, 232);
INSERT INTO User VALUES ("Cory Nguyen", "cory.nguyen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (229, 68, 241);
INSERT INTO User VALUES ("Claude George", "claude.george@gmail.com", "test1234");
INSERT INTO Athlete VALUES (230, 79, 172);
INSERT INTO User VALUES ("Erik Jacobs", "erik.jacobs@gmail.com", "test1234");
INSERT INTO Athlete VALUES (231, 78, 198);
INSERT INTO User VALUES ("Darryl Reid", "darryl.reid@gmail.com", "test1234");
INSERT INTO Athlete VALUES (232, 70, 172);
INSERT INTO User VALUES ("Jamie Kim", "jamie.kim@gmail.com", "test1234");
INSERT INTO Athlete VALUES (233, 69, 234);
INSERT INTO User VALUES ("Neil Fuller", "neil.fuller@gmail.com", "test1234");
INSERT INTO Athlete VALUES (234, 71, 186);
INSERT INTO User VALUES ("Jessie Lynch", "jessie.lynch@gmail.com", "test1234");
INSERT INTO Athlete VALUES (235, 65, 221);
INSERT INTO User VALUES ("Christian Dean", "christian.dean@gmail.com", "test1234");
INSERT INTO Athlete VALUES (236, 75, 234);
INSERT INTO User VALUES ("Javier Gilbert", "javier.gilbert@gmail.com", "test1234");
INSERT INTO Athlete VALUES (237, 71, 202);
INSERT INTO User VALUES ("Fernando Garrett", "fernando.garrett@gmail.com", "test1234");
INSERT INTO Athlete VALUES (238, 80, 156);
INSERT INTO User VALUES ("Clinton Romero", "clinton.romero@gmail.com", "test1234");
INSERT INTO Athlete VALUES (239, 67, 214);
INSERT INTO User VALUES ("Ted Welch", "ted.welch@gmail.com", "test1234");
INSERT INTO Athlete VALUES (240, 76, 167);
INSERT INTO User VALUES ("Mathew Larson", "mathew.larson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (241, 69, 212);
INSERT INTO User VALUES ("Tyrone Frazier", "tyrone.frazier@gmail.com", "test1234");
INSERT INTO Athlete VALUES (242, 80, 226);
INSERT INTO User VALUES ("Darren Burke", "darren.burke@gmail.com", "test1234");
INSERT INTO Athlete VALUES (243, 78, 163);
INSERT INTO User VALUES ("Lonnie Hanson", "lonnie.hanson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (244, 65, 204);
INSERT INTO User VALUES ("Lance Day", "lance.day@gmail.com", "test1234");
INSERT INTO Athlete VALUES (245, 66, 247);
INSERT INTO User VALUES ("Cody Mendoza", "cody.mendoza@gmail.com", "test1234");
INSERT INTO Athlete VALUES (246, 78, 201);
INSERT INTO User VALUES ("Julio Moreno", "julio.moreno@gmail.com", "test1234");
INSERT INTO Athlete VALUES (247, 80, 167);
INSERT INTO User VALUES ("Kelly Bowman", "kelly.bowman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (248, 67, 213);
INSERT INTO User VALUES ("Kurt Medina", "kurt.medina@gmail.com", "test1234");
INSERT INTO Athlete VALUES (249, 71, 193);
INSERT INTO User VALUES ("Allan Fowler", "allan.fowler@gmail.com", "test1234");
INSERT INTO Athlete VALUES (250, 76, 174);
INSERT INTO User VALUES ("Nelson Brewer", "nelson.brewer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (251, 65, 246);
INSERT INTO User VALUES ("Guy Hoffman", "guy.hoffman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (252, 66, 171);
INSERT INTO User VALUES ("Clayton Carlson", "clayton.carlson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (253, 67, 199);
INSERT INTO User VALUES ("Hugh Silva", "hugh.silva@gmail.com", "test1234");
INSERT INTO Athlete VALUES (254, 75, 231);
INSERT INTO User VALUES ("Max Pearson", "max.pearson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (255, 76, 191);
INSERT INTO User VALUES ("Dwayne Holland", "dwayne.holland@gmail.com", "test1234");
INSERT INTO Athlete VALUES (256, 80, 189);
INSERT INTO User VALUES ("Dwight Douglas", "dwight.douglas@gmail.com", "test1234");
INSERT INTO Athlete VALUES (257, 69, 214);
INSERT INTO User VALUES ("Armando Fleming", "armando.fleming@gmail.com", "test1234");
INSERT INTO Athlete VALUES (258, 69, 243);
INSERT INTO User VALUES ("Felix Jensen", "felix.jensen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (259, 69, 205);
INSERT INTO User VALUES ("Jimmie Vargas", "jimmie.vargas@gmail.com", "test1234");
INSERT INTO Athlete VALUES (260, 72, 225);
INSERT INTO User VALUES ("Everett Byrd", "everett.byrd@gmail.com", "test1234");
INSERT INTO Athlete VALUES (261, 75, 232);
INSERT INTO User VALUES ("Jordan Davidson", "jordan.davidson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (262, 74, 234);
INSERT INTO User VALUES ("Ian Hopkins", "ian.hopkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (263, 65, 174);
INSERT INTO User VALUES ("Wallace May", "wallace.may@gmail.com", "test1234");
INSERT INTO Athlete VALUES (264, 68, 227);
INSERT INTO User VALUES ("Ken Terry", "ken.terry@gmail.com", "test1234");
INSERT INTO Athlete VALUES (265, 74, 218);
INSERT INTO User VALUES ("Bob Herrera", "bob.herrera@gmail.com", "test1234");
INSERT INTO Athlete VALUES (266, 69, 219);
INSERT INTO User VALUES ("Jaime Wade", "jaime.wade@gmail.com", "test1234");
INSERT INTO Athlete VALUES (267, 66, 217);
INSERT INTO User VALUES ("Casey Soto", "casey.soto@gmail.com", "test1234");
INSERT INTO Athlete VALUES (268, 79, 201);
INSERT INTO User VALUES ("Alfredo Walters", "alfredo.walters@gmail.com", "test1234");
INSERT INTO Athlete VALUES (269, 68, 187);
INSERT INTO User VALUES ("Alberto Curtis", "alberto.curtis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (270, 69, 229);
INSERT INTO User VALUES ("Dave Neal", "dave.neal@gmail.com", "test1234");
INSERT INTO Athlete VALUES (271, 66, 233);
INSERT INTO User VALUES ("Ivan Caldwell", "ivan.caldwell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (272, 75, 219);
INSERT INTO User VALUES ("Johnnie Lowe", "johnnie.lowe@gmail.com", "test1234");
INSERT INTO Athlete VALUES (273, 80, 237);
INSERT INTO User VALUES ("Sidney Jennings", "sidney.jennings@gmail.com", "test1234");
INSERT INTO Athlete VALUES (274, 66, 212);
INSERT INTO User VALUES ("Byron Barnett", "byron.barnett@gmail.com", "test1234");
INSERT INTO Athlete VALUES (275, 76, 201);
INSERT INTO User VALUES ("Julian Graves", "julian.graves@gmail.com", "test1234");
INSERT INTO Athlete VALUES (276, 71, 176);
INSERT INTO User VALUES ("Isaac Jimenez", "isaac.jimenez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (277, 69, 216);
INSERT INTO User VALUES ("Morris Horton", "morris.horton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (278, 73, 225);
INSERT INTO User VALUES ("Clifton Shelton", "clifton.shelton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (279, 78, 184);
INSERT INTO User VALUES ("Willard Barrett", "willard.barrett@gmail.com", "test1234");
INSERT INTO Athlete VALUES (280, 67, 214);
INSERT INTO User VALUES ("Daryl Obrien", "daryl.obrien@gmail.com", "test1234");
INSERT INTO Athlete VALUES (281, 65, 219);
INSERT INTO User VALUES ("Ross Castro", "ross.castro@gmail.com", "test1234");
INSERT INTO Athlete VALUES (282, 72, 170);
INSERT INTO User VALUES ("Virgil Sutton", "virgil.sutton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (283, 69, 207);
INSERT INTO User VALUES ("Andy Gregory", "andy.gregory@gmail.com", "test1234");
INSERT INTO Athlete VALUES (284, 69, 161);
INSERT INTO User VALUES ("Marshall Mckinney", "marshall.mckinney@gmail.com", "test1234");
INSERT INTO Athlete VALUES (285, 78, 168);
INSERT INTO User VALUES ("Salvador Lucas", "salvador.lucas@gmail.com", "test1234");
INSERT INTO Athlete VALUES (286, 70, 240);
INSERT INTO User VALUES ("Perry Miles", "perry.miles@gmail.com", "test1234");
INSERT INTO Athlete VALUES (287, 76, 210);
INSERT INTO User VALUES ("Kirk Craig", "kirk.craig@gmail.com", "test1234");
INSERT INTO Athlete VALUES (288, 76, 192);
INSERT INTO User VALUES ("Sergio Rodriquez", "sergio.rodriquez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (289, 73, 177);
INSERT INTO User VALUES ("Marion Chambers", "marion.chambers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (290, 65, 242);
INSERT INTO User VALUES ("Tracy Holt", "tracy.holt@gmail.com", "test1234");
INSERT INTO Athlete VALUES (291, 80, 189);
INSERT INTO User VALUES ("Seth Lambert", "seth.lambert@gmail.com", "test1234");
INSERT INTO Athlete VALUES (292, 72, 166);
INSERT INTO User VALUES ("Kent Fletcher", "kent.fletcher@gmail.com", "test1234");
INSERT INTO Athlete VALUES (293, 77, 151);
INSERT INTO User VALUES ("Terrance Watts", "terrance.watts@gmail.com", "test1234");
INSERT INTO Athlete VALUES (294, 69, 167);
INSERT INTO User VALUES ("Rene Bates", "rene.bates@gmail.com", "test1234");
INSERT INTO Athlete VALUES (295, 71, 156);
INSERT INTO User VALUES ("Eduardo Hale", "eduardo.hale@gmail.com", "test1234");
INSERT INTO Athlete VALUES (296, 79, 221);
INSERT INTO User VALUES ("Terrence Rhodes", "terrence.rhodes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (297, 76, 203);
INSERT INTO User VALUES ("Enrique Pena", "enrique.pena@gmail.com", "test1234");
INSERT INTO Athlete VALUES (298, 80, 160);
INSERT INTO User VALUES ("Freddie Beck", "freddie.beck@gmail.com", "test1234");
INSERT INTO Athlete VALUES (299, 76, 158);
INSERT INTO User VALUES ("Wade Newman", "wade.newman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (300, 80, 216);
INSERT INTO User VALUES ("Austin Haynes", "austin.haynes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (301, 78, 180);
INSERT INTO User VALUES ("Stuart Mcdaniel", "stuart.mcdaniel@gmail.com", "test1234");
INSERT INTO Athlete VALUES (302, 73, 242);
INSERT INTO User VALUES ("Fredrick Mendez", "fredrick.mendez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (303, 66, 219);
INSERT INTO User VALUES ("Arturo Bush", "arturo.bush@gmail.com", "test1234");
INSERT INTO Athlete VALUES (304, 72, 176);
INSERT INTO User VALUES ("Alejandro Vaughn", "alejandro.vaughn@gmail.com", "test1234");
INSERT INTO Athlete VALUES (305, 78, 210);
INSERT INTO User VALUES ("Jackie Parks", "jackie.parks@gmail.com", "test1234");
INSERT INTO Athlete VALUES (306, 75, 220);
INSERT INTO User VALUES ("Joey Dawson", "joey.dawson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (307, 70, 208);
INSERT INTO User VALUES ("Nick Santiago", "nick.santiago@gmail.com", "test1234");
INSERT INTO Athlete VALUES (308, 70, 217);
INSERT INTO User VALUES ("Luther Norris", "luther.norris@gmail.com", "test1234");
INSERT INTO Athlete VALUES (309, 75, 156);
INSERT INTO User VALUES ("Wendell Hardy", "wendell.hardy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (310, 73, 181);
INSERT INTO User VALUES ("Jeremiah Love", "jeremiah.love@gmail.com", "test1234");
INSERT INTO Athlete VALUES (311, 65, 173);
INSERT INTO User VALUES ("Evan Steele", "evan.steele@gmail.com", "test1234");
INSERT INTO Athlete VALUES (312, 76, 151);
INSERT INTO User VALUES ("Julius Curry", "julius.curry@gmail.com", "test1234");
INSERT INTO Athlete VALUES (313, 76, 210);
INSERT INTO User VALUES ("Dana Powers", "dana.powers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (314, 79, 212);
INSERT INTO User VALUES ("Donnie Schultz", "donnie.schultz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (315, 76, 232);
INSERT INTO User VALUES ("Otis Barker", "otis.barker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (316, 77, 154);
INSERT INTO User VALUES ("Shannon Guzman", "shannon.guzman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (317, 78, 229);
INSERT INTO User VALUES ("Trevor Page", "trevor.page@gmail.com", "test1234");
INSERT INTO Athlete VALUES (318, 68, 176);
INSERT INTO User VALUES ("Oliver Munoz", "oliver.munoz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (319, 73, 156);
INSERT INTO User VALUES ("Luke Ball", "luke.ball@gmail.com", "test1234");
INSERT INTO Athlete VALUES (320, 74, 216);
INSERT INTO User VALUES ("Homer Keller", "homer.keller@gmail.com", "test1234");
INSERT INTO Athlete VALUES (321, 74, 163);
INSERT INTO User VALUES ("Gerard Chandler", "gerard.chandler@gmail.com", "test1234");
INSERT INTO Athlete VALUES (322, 74, 161);
INSERT INTO User VALUES ("Doug Weber", "doug.weber@gmail.com", "test1234");
INSERT INTO Athlete VALUES (323, 79, 233);
INSERT INTO User VALUES ("Kenny Leonard", "kenny.leonard@gmail.com", "test1234");
INSERT INTO Athlete VALUES (324, 71, 213);
INSERT INTO User VALUES ("Hubert Walsh", "hubert.walsh@gmail.com", "test1234");
INSERT INTO Athlete VALUES (325, 67, 166);
INSERT INTO User VALUES ("Angelo Lyons", "angelo.lyons@gmail.com", "test1234");
INSERT INTO Athlete VALUES (326, 74, 151);
INSERT INTO User VALUES ("Shaun Ramsey", "shaun.ramsey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (327, 71, 195);
INSERT INTO User VALUES ("Lyle Wolfe", "lyle.wolfe@gmail.com", "test1234");
INSERT INTO Athlete VALUES (328, 78, 151);
INSERT INTO User VALUES ("Matt Schneider", "matt.schneider@gmail.com", "test1234");
INSERT INTO Athlete VALUES (329, 70, 200);
INSERT INTO User VALUES ("Lynn Mullins", "lynn.mullins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (330, 69, 237);
INSERT INTO User VALUES ("Alfonso Benson", "alfonso.benson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (331, 77, 185);
INSERT INTO User VALUES ("Orlando Sharp", "orlando.sharp@gmail.com", "test1234");
INSERT INTO Athlete VALUES (332, 72, 236);
INSERT INTO User VALUES ("Rex Bowen", "rex.bowen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (333, 79, 226);
INSERT INTO User VALUES ("Carlton Daniel", "carlton.daniel@gmail.com", "test1234");
INSERT INTO Athlete VALUES (334, 74, 226);
INSERT INTO User VALUES ("Ernesto Barber", "ernesto.barber@gmail.com", "test1234");
INSERT INTO Athlete VALUES (335, 70, 160);
INSERT INTO User VALUES ("Cameron Cummings", "cameron.cummings@gmail.com", "test1234");
INSERT INTO Athlete VALUES (336, 80, 156);
INSERT INTO User VALUES ("Neal Hines", "neal.hines@gmail.com", "test1234");
INSERT INTO Athlete VALUES (337, 77, 218);
INSERT INTO User VALUES ("Pablo Baldwin", "pablo.baldwin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (338, 70, 231);
INSERT INTO User VALUES ("Lorenzo Griffith", "lorenzo.griffith@gmail.com", "test1234");
INSERT INTO Athlete VALUES (339, 68, 216);
INSERT INTO User VALUES ("Omar Valdez", "omar.valdez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (340, 78, 183);
INSERT INTO User VALUES ("Wilbur Hubbard", "wilbur.hubbard@gmail.com", "test1234");
INSERT INTO Athlete VALUES (341, 74, 172);
INSERT INTO User VALUES ("Blake Salazar", "blake.salazar@gmail.com", "test1234");
INSERT INTO Athlete VALUES (342, 79, 161);
INSERT INTO User VALUES ("Grant Reeves", "grant.reeves@gmail.com", "test1234");
INSERT INTO Athlete VALUES (343, 65, 246);
INSERT INTO User VALUES ("Horace Warner", "horace.warner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (344, 67, 239);
INSERT INTO User VALUES ("Roderick Stevenson", "roderick.stevenson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (345, 66, 191);
INSERT INTO User VALUES ("Kerry Burgess", "kerry.burgess@gmail.com", "test1234");
INSERT INTO Athlete VALUES (346, 70, 210);
INSERT INTO User VALUES ("Abraham Santos", "abraham.santos@gmail.com", "test1234");
INSERT INTO Athlete VALUES (347, 75, 154);
INSERT INTO User VALUES ("Willis Tate", "willis.tate@gmail.com", "test1234");
INSERT INTO Athlete VALUES (348, 77, 239);
INSERT INTO User VALUES ("Rickey Cross", "rickey.cross@gmail.com", "test1234");
INSERT INTO Athlete VALUES (349, 70, 244);
INSERT INTO User VALUES ("Jean Garner", "jean.garner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (350, 65, 203);
INSERT INTO User VALUES ("Ira Mann", "ira.mann@gmail.com", "test1234");
INSERT INTO Athlete VALUES (351, 74, 158);
INSERT INTO User VALUES ("Andres Mack", "andres.mack@gmail.com", "test1234");
INSERT INTO Athlete VALUES (352, 73, 175);
INSERT INTO User VALUES ("Cesar Moss", "cesar.moss@gmail.com", "test1234");
INSERT INTO Athlete VALUES (353, 72, 238);
INSERT INTO User VALUES ("Johnathan Thornton", "johnathan.thornton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (354, 79, 156);
INSERT INTO User VALUES ("Malcolm Dennis", "malcolm.dennis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (355, 78, 207);
INSERT INTO User VALUES ("Rudolph Mcgee", "rudolph.mcgee@gmail.com", "test1234");
INSERT INTO Athlete VALUES (356, 80, 190);
INSERT INTO User VALUES ("Damon Farmer", "damon.farmer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (357, 66, 168);
INSERT INTO User VALUES ("Kelvin Delgado", "kelvin.delgado@gmail.com", "test1234");
INSERT INTO Athlete VALUES (358, 76, 238);
INSERT INTO User VALUES ("Rudy Aguilar", "rudy.aguilar@gmail.com", "test1234");
INSERT INTO Athlete VALUES (359, 78, 196);
INSERT INTO User VALUES ("Preston Vega", "preston.vega@gmail.com", "test1234");
INSERT INTO Athlete VALUES (360, 80, 192);
INSERT INTO User VALUES ("Alton Glover", "alton.glover@gmail.com", "test1234");
INSERT INTO Athlete VALUES (361, 68, 220);
INSERT INTO User VALUES ("Archie Manning", "archie.manning@gmail.com", "test1234");
INSERT INTO Athlete VALUES (362, 65, 210);
INSERT INTO User VALUES ("Marco Cohen", "marco.cohen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (363, 73, 233);
INSERT INTO User VALUES ("Wm Harmon", "wm.harmon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (364, 69, 195);
INSERT INTO User VALUES ("Pete Rodgers", "pete.rodgers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (365, 79, 233);
INSERT INTO User VALUES ("Randolph Robbins", "randolph.robbins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (366, 74, 246);
INSERT INTO User VALUES ("Garry Newton", "garry.newton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (367, 66, 177);
INSERT INTO User VALUES ("Geoffrey Todd", "geoffrey.todd@gmail.com", "test1234");
INSERT INTO Athlete VALUES (368, 80, 195);
INSERT INTO User VALUES ("Jonathon Blair", "jonathon.blair@gmail.com", "test1234");
INSERT INTO Athlete VALUES (369, 73, 188);
INSERT INTO User VALUES ("Felipe Higgins", "felipe.higgins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (370, 73, 241);
INSERT INTO User VALUES ("Bennie Ingram", "bennie.ingram@gmail.com", "test1234");
INSERT INTO Athlete VALUES (371, 76, 211);
INSERT INTO User VALUES ("Gerardo Reese", "gerardo.reese@gmail.com", "test1234");
INSERT INTO Athlete VALUES (372, 72, 180);
INSERT INTO User VALUES ("Ed Cannon", "ed.cannon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (373, 74, 160);
INSERT INTO User VALUES ("Dominic Strickland", "dominic.strickland@gmail.com", "test1234");
INSERT INTO Athlete VALUES (374, 78, 202);
INSERT INTO User VALUES ("Robin Townsend", "robin.townsend@gmail.com", "test1234");
INSERT INTO Athlete VALUES (375, 74, 235);
INSERT INTO User VALUES ("Loren Potter", "loren.potter@gmail.com", "test1234");
INSERT INTO Athlete VALUES (376, 70, 187);
INSERT INTO User VALUES ("Delbert Goodwin", "delbert.goodwin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (377, 66, 205);
INSERT INTO User VALUES ("Colin Walton", "colin.walton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (378, 66, 163);
INSERT INTO User VALUES ("Guillermo Rowe", "guillermo.rowe@gmail.com", "test1234");
INSERT INTO Athlete VALUES (379, 78, 192);
INSERT INTO User VALUES ("Earnest Hampton", "earnest.hampton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (380, 76, 152);
INSERT INTO User VALUES ("Lucas Ortega", "lucas.ortega@gmail.com", "test1234");
INSERT INTO Athlete VALUES (381, 71, 196);
INSERT INTO User VALUES ("Benny Patton", "benny.patton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (382, 75, 156);
INSERT INTO User VALUES ("Noel Swanson", "noel.swanson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (383, 80, 174);
INSERT INTO User VALUES ("Spencer Joseph", "spencer.joseph@gmail.com", "test1234");
INSERT INTO Athlete VALUES (384, 65, 174);
INSERT INTO User VALUES ("Rodolfo Francis", "rodolfo.francis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (385, 78, 200);
INSERT INTO User VALUES ("Myron Goodman", "myron.goodman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (386, 77, 166);
INSERT INTO User VALUES ("Edmund Maldonado", "edmund.maldonado@gmail.com", "test1234");
INSERT INTO Athlete VALUES (387, 79, 157);
INSERT INTO User VALUES ("Garrett Yates", "garrett.yates@gmail.com", "test1234");
INSERT INTO Athlete VALUES (388, 70, 216);
INSERT INTO User VALUES ("Salvatore Becker", "salvatore.becker@gmail.com", "test1234");
INSERT INTO Athlete VALUES (389, 75, 156);
INSERT INTO User VALUES ("Cedric Erickson", "cedric.erickson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (390, 69, 159);
INSERT INTO User VALUES ("Lowell Hodges", "lowell.hodges@gmail.com", "test1234");
INSERT INTO Athlete VALUES (391, 80, 202);
INSERT INTO User VALUES ("Gregg Rios", "gregg.rios@gmail.com", "test1234");
INSERT INTO Athlete VALUES (392, 74, 160);
INSERT INTO User VALUES ("Sherman Conner", "sherman.conner@gmail.com", "test1234");
INSERT INTO Athlete VALUES (393, 67, 216);
INSERT INTO User VALUES ("Wilson Adkins", "wilson.adkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (394, 67, 171);
INSERT INTO User VALUES ("Devin Webster", "devin.webster@gmail.com", "test1234");
INSERT INTO Athlete VALUES (395, 67, 199);
INSERT INTO User VALUES ("Sylvester Norman", "sylvester.norman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (396, 80, 168);
INSERT INTO User VALUES ("Kim Malone", "kim.malone@gmail.com", "test1234");
INSERT INTO Athlete VALUES (397, 78, 161);
INSERT INTO User VALUES ("Roosevelt Hammond", "roosevelt.hammond@gmail.com", "test1234");
INSERT INTO Athlete VALUES (398, 77, 189);
INSERT INTO User VALUES ("Israel Flowers", "israel.flowers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (399, 79, 237);
INSERT INTO User VALUES ("Jermaine Cobb", "jermaine.cobb@gmail.com", "test1234");
INSERT INTO Athlete VALUES (400, 71, 226);
INSERT INTO User VALUES ("Forrest Moody", "forrest.moody@gmail.com", "test1234");
INSERT INTO Athlete VALUES (401, 70, 182);
INSERT INTO User VALUES ("Wilbert Quinn", "wilbert.quinn@gmail.com", "test1234");
INSERT INTO Athlete VALUES (402, 71, 193);
INSERT INTO User VALUES ("Leland Blake", "leland.blake@gmail.com", "test1234");
INSERT INTO Athlete VALUES (403, 72, 250);
INSERT INTO User VALUES ("Simon Maxwell", "simon.maxwell@gmail.com", "test1234");
INSERT INTO Athlete VALUES (404, 75, 173);
INSERT INTO User VALUES ("Guadalupe Pope", "guadalupe.pope@gmail.com", "test1234");
INSERT INTO Athlete VALUES (405, 76, 177);
INSERT INTO User VALUES ("Clark Floyd", "clark.floyd@gmail.com", "test1234");
INSERT INTO Athlete VALUES (406, 77, 163);
INSERT INTO User VALUES ("Irving Osborne", "irving.osborne@gmail.com", "test1234");
INSERT INTO Athlete VALUES (407, 67, 211);
INSERT INTO User VALUES ("Carroll Paul", "carroll.paul@gmail.com", "test1234");
INSERT INTO Athlete VALUES (408, 72, 209);
INSERT INTO User VALUES ("Bryant Mccarthy", "bryant.mccarthy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (409, 73, 199);
INSERT INTO User VALUES ("Owen Guerrero", "owen.guerrero@gmail.com", "test1234");
INSERT INTO Athlete VALUES (410, 78, 193);
INSERT INTO User VALUES ("Rufus Lindsey", "rufus.lindsey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (411, 76, 243);
INSERT INTO User VALUES ("Woodrow Estrada", "woodrow.estrada@gmail.com", "test1234");
INSERT INTO Athlete VALUES (412, 75, 177);
INSERT INTO User VALUES ("Sammy Sandoval", "sammy.sandoval@gmail.com", "test1234");
INSERT INTO Athlete VALUES (413, 66, 241);
INSERT INTO User VALUES ("Kristopher Gibbs", "kristopher.gibbs@gmail.com", "test1234");
INSERT INTO Athlete VALUES (414, 78, 221);
INSERT INTO User VALUES ("Mack Tyler", "mack.tyler@gmail.com", "test1234");
INSERT INTO Athlete VALUES (415, 77, 170);
INSERT INTO User VALUES ("Levi Gross", "levi.gross@gmail.com", "test1234");
INSERT INTO Athlete VALUES (416, 67, 193);
INSERT INTO User VALUES ("Marcos Fitzgerald", "marcos.fitzgerald@gmail.com", "test1234");
INSERT INTO Athlete VALUES (417, 72, 238);
INSERT INTO User VALUES ("Gustavo Stokes", "gustavo.stokes@gmail.com", "test1234");
INSERT INTO Athlete VALUES (418, 76, 190);
INSERT INTO User VALUES ("Jake Doyle", "jake.doyle@gmail.com", "test1234");
INSERT INTO Athlete VALUES (419, 73, 227);
INSERT INTO User VALUES ("Lionel Sherman", "lionel.sherman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (420, 75, 225);
INSERT INTO User VALUES ("Marty Saunders", "marty.saunders@gmail.com", "test1234");
INSERT INTO Athlete VALUES (421, 80, 190);
INSERT INTO User VALUES ("Taylor Wise", "taylor.wise@gmail.com", "test1234");
INSERT INTO Athlete VALUES (422, 79, 223);
INSERT INTO User VALUES ("Ellis Colon", "ellis.colon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (423, 79, 153);
INSERT INTO User VALUES ("Dallas Gill", "dallas.gill@gmail.com", "test1234");
INSERT INTO Athlete VALUES (424, 67, 249);
INSERT INTO User VALUES ("Gilberto Alvarado", "gilberto.alvarado@gmail.com", "test1234");
INSERT INTO Athlete VALUES (425, 79, 210);
INSERT INTO User VALUES ("Clint Greer", "clint.greer@gmail.com", "test1234");
INSERT INTO Athlete VALUES (426, 67, 153);
INSERT INTO User VALUES ("Nicolas Padilla", "nicolas.padilla@gmail.com", "test1234");
INSERT INTO Athlete VALUES (427, 75, 208);
INSERT INTO User VALUES ("Laurence Simon", "laurence.simon@gmail.com", "test1234");
INSERT INTO Athlete VALUES (428, 68, 238);
INSERT INTO User VALUES ("Ismael Waters", "ismael.waters@gmail.com", "test1234");
INSERT INTO Athlete VALUES (429, 69, 226);
INSERT INTO User VALUES ("Orville Nunez", "orville.nunez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (430, 70, 216);
INSERT INTO User VALUES ("Drew Ballard", "drew.ballard@gmail.com", "test1234");
INSERT INTO Athlete VALUES (431, 72, 229);
INSERT INTO User VALUES ("Jody Schwartz", "jody.schwartz@gmail.com", "test1234");
INSERT INTO Athlete VALUES (432, 79, 188);
INSERT INTO User VALUES ("Ervin Mcbride", "ervin.mcbride@gmail.com", "test1234");
INSERT INTO Athlete VALUES (433, 76, 162);
INSERT INTO User VALUES ("Dewey Houston", "dewey.houston@gmail.com", "test1234");
INSERT INTO Athlete VALUES (434, 65, 178);
INSERT INTO User VALUES ("Al Christensen", "al.christensen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (435, 72, 182);
INSERT INTO User VALUES ("Wilfred Klein", "wilfred.klein@gmail.com", "test1234");
INSERT INTO Athlete VALUES (436, 69, 184);
INSERT INTO User VALUES ("Josh Pratt", "josh.pratt@gmail.com", "test1234");
INSERT INTO Athlete VALUES (437, 72, 246);
INSERT INTO User VALUES ("Hugo Briggs", "hugo.briggs@gmail.com", "test1234");
INSERT INTO Athlete VALUES (438, 72, 170);
INSERT INTO User VALUES ("Ignacio Parsons", "ignacio.parsons@gmail.com", "test1234");
INSERT INTO Athlete VALUES (439, 70, 208);
INSERT INTO User VALUES ("Caleb Mclaughlin", "caleb.mclaughlin@gmail.com", "test1234");
INSERT INTO Athlete VALUES (440, 78, 232);
INSERT INTO User VALUES ("Tomas Zimmerman", "tomas.zimmerman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (441, 77, 225);
INSERT INTO User VALUES ("Sheldon French", "sheldon.french@gmail.com", "test1234");
INSERT INTO Athlete VALUES (442, 68, 172);
INSERT INTO User VALUES ("Erick Buchanan", "erick.buchanan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (443, 67, 248);
INSERT INTO User VALUES ("Frankie Moran", "frankie.moran@gmail.com", "test1234");
INSERT INTO Athlete VALUES (444, 69, 228);
INSERT INTO User VALUES ("Stewart Copeland", "stewart.copeland@gmail.com", "test1234");
INSERT INTO Athlete VALUES (445, 77, 230);
INSERT INTO User VALUES ("Doyle Roy", "doyle.roy@gmail.com", "test1234");
INSERT INTO Athlete VALUES (446, 73, 206);
INSERT INTO User VALUES ("Darrel Pittman", "darrel.pittman@gmail.com", "test1234");
INSERT INTO Athlete VALUES (447, 70, 243);
INSERT INTO User VALUES ("Rogelio Brady", "rogelio.brady@gmail.com", "test1234");
INSERT INTO Athlete VALUES (448, 73, 202);
INSERT INTO User VALUES ("Terence Mccormick", "terence.mccormick@gmail.com", "test1234");
INSERT INTO Athlete VALUES (449, 78, 186);
INSERT INTO User VALUES ("Santiago Holloway", "santiago.holloway@gmail.com", "test1234");
INSERT INTO Athlete VALUES (450, 73, 175);
INSERT INTO User VALUES ("Alonzo Brock", "alonzo.brock@gmail.com", "test1234");
INSERT INTO Athlete VALUES (451, 71, 224);
INSERT INTO User VALUES ("Elias Poole", "elias.poole@gmail.com", "test1234");
INSERT INTO Athlete VALUES (452, 79, 232);
INSERT INTO User VALUES ("Bert Frank", "bert.frank@gmail.com", "test1234");
INSERT INTO Athlete VALUES (453, 79, 207);
INSERT INTO User VALUES ("Elbert Logan", "elbert.logan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (454, 67, 225);
INSERT INTO User VALUES ("Ramiro Owen", "ramiro.owen@gmail.com", "test1234");
INSERT INTO Athlete VALUES (455, 68, 231);
INSERT INTO User VALUES ("Conrad Bass", "conrad.bass@gmail.com", "test1234");
INSERT INTO Athlete VALUES (456, 68, 195);
INSERT INTO User VALUES ("Pat Marsh", "pat.marsh@gmail.com", "test1234");
INSERT INTO Athlete VALUES (457, 76, 200);
INSERT INTO User VALUES ("Noah Drake", "noah.drake@gmail.com", "test1234");
INSERT INTO Athlete VALUES (458, 71, 206);
INSERT INTO User VALUES ("Grady Wong", "grady.wong@gmail.com", "test1234");
INSERT INTO Athlete VALUES (459, 79, 198);
INSERT INTO User VALUES ("Phil Jefferson", "phil.jefferson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (460, 68, 226);
INSERT INTO User VALUES ("Cornelius Park", "cornelius.park@gmail.com", "test1234");
INSERT INTO Athlete VALUES (461, 76, 207);
INSERT INTO User VALUES ("Lamar Morton", "lamar.morton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (462, 66, 206);
INSERT INTO User VALUES ("Rolando Abbott", "rolando.abbott@gmail.com", "test1234");
INSERT INTO Athlete VALUES (463, 72, 198);
INSERT INTO User VALUES ("Clay Sparks", "clay.sparks@gmail.com", "test1234");
INSERT INTO Athlete VALUES (464, 71, 208);
INSERT INTO User VALUES ("Percy Patrick", "percy.patrick@gmail.com", "test1234");
INSERT INTO Athlete VALUES (465, 69, 151);
INSERT INTO User VALUES ("Dexter Norton", "dexter.norton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (466, 72, 189);
INSERT INTO User VALUES ("Bradford Huff", "bradford.huff@gmail.com", "test1234");
INSERT INTO Athlete VALUES (467, 80, 190);
INSERT INTO User VALUES ("Merle Clayton", "merle.clayton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (468, 80, 224);
INSERT INTO User VALUES ("Darin Massey", "darin.massey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (469, 68, 176);
INSERT INTO User VALUES ("Amos Lloyd", "amos.lloyd@gmail.com", "test1234");
INSERT INTO Athlete VALUES (470, 73, 164);
INSERT INTO User VALUES ("Terrell Figueroa", "terrell.figueroa@gmail.com", "test1234");
INSERT INTO Athlete VALUES (471, 76, 216);
INSERT INTO User VALUES ("Moses Carson", "moses.carson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (472, 66, 208);
INSERT INTO User VALUES ("Irvin Bowers", "irvin.bowers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (473, 72, 212);
INSERT INTO User VALUES ("Saul Roberson", "saul.roberson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (474, 66, 241);
INSERT INTO User VALUES ("Roman Barton", "roman.barton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (475, 79, 154);
INSERT INTO User VALUES ("Darnell Tran", "darnell.tran@gmail.com", "test1234");
INSERT INTO Athlete VALUES (476, 72, 214);
INSERT INTO User VALUES ("Randal Lamb", "randal.lamb@gmail.com", "test1234");
INSERT INTO Athlete VALUES (477, 71, 241);
INSERT INTO User VALUES ("Tommie Harrington", "tommie.harrington@gmail.com", "test1234");
INSERT INTO Athlete VALUES (478, 68, 218);
INSERT INTO User VALUES ("Timmy Casey", "timmy.casey@gmail.com", "test1234");
INSERT INTO Athlete VALUES (479, 75, 171);
INSERT INTO User VALUES ("Darrin Boone", "darrin.boone@gmail.com", "test1234");
INSERT INTO Athlete VALUES (480, 76, 185);
INSERT INTO User VALUES ("Winston Cortez", "winston.cortez@gmail.com", "test1234");
INSERT INTO Athlete VALUES (481, 80, 200);
INSERT INTO User VALUES ("Brendan Clarke", "brendan.clarke@gmail.com", "test1234");
INSERT INTO Athlete VALUES (482, 74, 173);
INSERT INTO User VALUES ("Toby Mathis", "toby.mathis@gmail.com", "test1234");
INSERT INTO Athlete VALUES (483, 80, 229);
INSERT INTO User VALUES ("Van Singleton", "van.singleton@gmail.com", "test1234");
INSERT INTO Athlete VALUES (484, 78, 229);
INSERT INTO User VALUES ("Abel Wilkins", "abel.wilkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (485, 73, 236);
INSERT INTO User VALUES ("Dominick Cain", "dominick.cain@gmail.com", "test1234");
INSERT INTO Athlete VALUES (486, 79, 209);
INSERT INTO User VALUES ("Boyd Bryan", "boyd.bryan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (487, 75, 154);
INSERT INTO User VALUES ("Courtney Underwood", "courtney.underwood@gmail.com", "test1234");
INSERT INTO Athlete VALUES (488, 80, 250);
INSERT INTO User VALUES ("Jan Hogan", "jan.hogan@gmail.com", "test1234");
INSERT INTO Athlete VALUES (489, 67, 205);
INSERT INTO User VALUES ("Emilio Mckenzie", "emilio.mckenzie@gmail.com", "test1234");
INSERT INTO Athlete VALUES (490, 78, 196);
INSERT INTO User VALUES ("Elijah Collier", "elijah.collier@gmail.com", "test1234");
INSERT INTO Athlete VALUES (491, 76, 200);
INSERT INTO User VALUES ("Cary Luna", "cary.luna@gmail.com", "test1234");
INSERT INTO Athlete VALUES (492, 71, 205);
INSERT INTO User VALUES ("Domingo Phelps", "domingo.phelps@gmail.com", "test1234");
INSERT INTO Athlete VALUES (493, 66, 204);
INSERT INTO User VALUES ("Santos Mcguire", "santos.mcguire@gmail.com", "test1234");
INSERT INTO Athlete VALUES (494, 72, 250);
INSERT INTO User VALUES ("Aubrey Allison", "aubrey.allison@gmail.com", "test1234");
INSERT INTO Athlete VALUES (495, 80, 199);
INSERT INTO User VALUES ("Emmett Bridges", "emmett.bridges@gmail.com", "test1234");
INSERT INTO Athlete VALUES (496, 76, 170);
INSERT INTO User VALUES ("Marlon Wilkerson", "marlon.wilkerson@gmail.com", "test1234");
INSERT INTO Athlete VALUES (497, 74, 245);
INSERT INTO User VALUES ("Emanuel Nash", "emanuel.nash@gmail.com", "test1234");
INSERT INTO Athlete VALUES (498, 71, 155);
INSERT INTO User VALUES ("Jerald Summers", "jerald.summers@gmail.com", "test1234");
INSERT INTO Athlete VALUES (499, 69, 250);
INSERT INTO User VALUES ("Edmond Atkins", "edmond.atkins@gmail.com", "test1234");
INSERT INTO Athlete VALUES (500, 70, 165);
